"""add youtube video fields

Revision ID: 5b920c8b243e
Revises: df92740afa81
Create Date: 2026-06-23 14:03:07.263856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b920c8b243e'
down_revision: Union[str, None] = 'df92740afa81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'duration_seconds')
    op.drop_column('posts', 'thumbnail_url')
    # ### end Alembic commands ###
