"""initial schema

Revision ID: df92740afa81
Revises: 
Create Date: 2026-06-23 12:07:21.985814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df92740afa81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funnel_assumptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=False),
    sa.Column('visit_rate', sa.Float(), nullable=False),
    sa.Column('demo_rate', sa.Float(), nullable=False),
    sa.Column('deal_value', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'running'"), nullable=False),
    sa.Column('posts_seen', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('posts_new', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('snapshots_taken', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_runs_started', 'job_runs', ['started_at'], unique=False)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idea_text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('format', sa.String(length=60), nullable=True),
    sa.Column('hook_type', sa.String(length=120), nullable=True),
    sa.Column('angle', sa.String(length=120), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendations_created', 'recommendations', ['created_at'], unique=False)
    op.create_index('ix_recommendations_cycle', 'recommendations', ['cycle_id'], unique=False)
    op.create_table('attribute_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('format', sa.String(length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('hook_type', sa.String(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('angle', sa.String(length=120), server_default=sa.text("''"), nullable=False),
    sa.Column('avg_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('sample_size', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('trend', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'topic', 'format', 'hook_type', 'angle', name='uq_attribute_combo')
    )
    op.create_table('funnel_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.String(length=40), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reach', sa.Float(), nullable=False),
    sa.Column('est_clicks', sa.Float(), nullable=False),
    sa.Column('est_visits', sa.Float(), nullable=False),
    sa.Column('est_demos', sa.Float(), nullable=False),
    sa.Column('est_pipeline_value', sa.Float(), nullable=False),
    sa.Column('assumptions_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assumptions_id'], ['funnel_assumptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_funnel_snapshots_cycle', 'funnel_snapshots', ['cycle_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('external_key', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'external_key', name='uq_source_platform_key')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('is_client', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'external_id', name='uq_post_platform_external')
    )
    op.create_index('ix_posts_client_posted', 'posts', ['is_client', 'posted_at'], unique=False)
    op.create_index('ix_posts_source_posted', 'posts', ['source_id', 'posted_at'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('awards', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_post_time', 'metric_snapshots', ['post_id', 'captured_at'], unique=False)
    op.create_index('ix_snapshots_time', 'metric_snapshots', ['captured_at'], unique=False)
    op.create_table('post_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('hook_type', sa.String(length=120), nullable=True),
    sa.Column('angle', sa.String(length=120), nullable=True),
    sa.Column('format', sa.String(length=60), nullable=True),
    sa.Column('classifier_version', sa.String(length=40), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'classifier_version', name='uq_classification_post_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_classifications')
    op.drop_index('ix_snapshots_time', table_name='metric_snapshots')
    op.drop_index('ix_snapshots_post_time', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index('ix_posts_source_posted', table_name='posts')
    op.drop_index('ix_posts_client_posted', table_name='posts')
    op.drop_table('posts')
    op.drop_table('sources')
    op.drop_index('ix_funnel_snapshots_cycle', table_name='funnel_snapshots')
    op.drop_table('funnel_snapshots')
    op.drop_table('attribute_performance')
    op.drop_index('ix_recommendations_cycle', table_name='recommendations')
    op.drop_index('ix_recommendations_created', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('platforms')
    op.drop_index('ix_job_runs_started', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_table('funnel_assumptions')
    # ### end Alembic commands ###
